### ISSUE TITLE
Error when zooming in/out with Google 3D Tiles layer

### ISSUE THREAD

**Issue by Biouche** [ebeaufay/UltraGlobe#14]
Hello,

First I wanted to thank you @ebeaufay for sharing this project, it is amazing.

As I started implelenting you solution in my project, I realized an error is continuously logged when using Google 3D Tiles layer and zooming in or out of the globe.

This error can also be reproduced on your demo website for Google 3D tiles : [https://www.jdultra.com/mapTiles/index.html](url)

![image](https://github.com/user-attachments/assets/a07b8006-4b60-478d-b586-9957d79cc9d9)

Hope this can help you solve an unidentified problem.

Regards,
Bioush

**Comment by ebeaufay** [comment]
Thanks.
this is actually normal. When you zoom in or out, a tile that's being fetched asynchronously may not be needed anymore hence the request is aborted. I will look to hide the error message. I don't hide it because I want to be notified of other fetch errors so for now I found it sufficient to have the "user aborted a request" message next to it
