### ISSUE TITLE
TypeError: cli.isMultipleCompiler is not a function

### ISSUE THREAD

**Issue by markokitanoski1** [ebeaufay/UltraGlobe#7]
While running `npm run dev` I am getting following error:

TypeError: cli.isMultipleCompiler is not a function

**Comment by ebeaufay** [comment]
hi, did you pull the latest code or are you using the "getting started" sample project? that way I can try to reproduce

**Comment by markokitanoski1** [comment]
While cloning root UltraGlobe repo and building installing npm dependencies with a Node version v14.21.3 & after running `npm run dev`, the following error is thrown:

` TypeError: cli.isMultipleCompiler is not a function`

**Comment by ebeaufay** [comment]
Perhaps use this project instead rather than cloning https://drive.google.com/file/d/1ECn7C98WRZRlaNhz_CG5sVFWkwG4mvTb/view?usp=share_link

The webpack config is simpler, if you clone the repo there's a setup for building the library which you probably don't need

Also I use NPM 16, not sure if that's going to change things but latest LTS version is even 18 and webpack does sometimes introduce breaking changes with older node versions
